### ISSUE TITLE
So… PSVR2?

### ISSUE THREAD

**Issue by aftrmth728** [alvr-org/alvr-visionos#143]
I appreciate that this was literally just announced, but I’m relatively clueless with this and I’ve seen that @shinyquagsire23 has been quite responsive around ALVR/Vision Pro discussion so I thought it was worth asking. Do you think the PSVR2 Sense controller support could be implemented for ALVR? I use surreal touch right now but they’re not great in my opinion. 

Also, a huge thanks for your work on ALVR for Vision Pro, I’ve spent many hours using it.

**Comment by pvspreetham** [comment]
Honestly, this is the first thing I thought about while watching the WWDC. Would be a neat feature.

**Comment by shinyquagsire23** [comment]
Yeah don't worry I've got PSVR2 controllers so it's happening, ETA ~a week-ish. I suspect some tech debt might have caught up with me with how I handled ARKit, so it might be more involved than I'd expected.

**Comment by ant2002k** [comment]
I would be happy to test!

**Comment by ant2002k** [comment]
It’s been released already by this GOAT coder (@shinyquagsire23 ) via TestFlight

https://testflight.apple.com/join/YoK2nuX6

**Comment by ant2002k** [comment]
Thanks.  Hopefully it’ll resolve in future Xcode/VisionOS betas.  I’ve read on Reddit that one can downgrade to H264 3200x3200 h264 at 100 mbit and it’ll work.   I just tested h265 on OS26 with the App Store ALVR build this morning in Steam VR Home for like 5 minutes… all seemed well. I use max panel Res there on the streamer and max 200mbit. I’ll try again this weekend 

RTX50 series drivers are buggy AF that doesn’t help either.  Something tells me you’ll figure it out though :)

**Comment by VoodooDE** [comment]
I just got my Apple Vision Pro and I connected the PSVR2 controllers to the AVP, it works. However when I start ALVR the virtual Quest controllers are shown and they are stuck to the ground in the middle of the SteamVR environment and they don't move. However they react when I push the buttons and thumbsticks on my PSVR2 controllers.
What am I doing wrong?

**Comment by ant2002k** [comment]
This issue was fixed by Apple in Beta 5.

**Comment by VoodooDE** [comment]
Hey there,
so now after installing the lastest Beta IOS on the Vision Pro, I still have the same problem!
The PSVR2 Controllers are connected to the AVP and I can also use them to navigate through the AVP menu.
However when I start ALVR on the AVP (Version 20.13.0) and the PC-Streamer (Version 20.14.1) I can connect the AVP and SteamVR starts. The problem is that the controllers are stuck on the ground in the middle and the PSVR2 controllers are not recognized. When I put them away SteamVR recognizes my hands as controllers, so it's set to hand-tracking or so? I deactivated all hand-tracking settings in the PC streamer software that I could find, but I'm sure I do something wrong. Can sb explain step-by-step how to connect the PSVR2 controllers and setup ALVR so that it works in SteamVR?
Thanks

**Comment by hrgargi** [comment]
The testflight is stopping in 7 days. Will there be an official implementing in the code (20.14 maybe)?

**Comment by hrgargi** [comment]
> > Hi Voodoo! You are sure you have the Testflight Version installed instead of the Appstore download? The Testflight is working with the PSVR2 Controllers. You then just have to rotate them a bit in the Streamer Software.
> 
> Hmm good question. So I went via the testflight link and accepted the terms. Where exactly do I have to install the testflight version then? I guess searching it in the store is wrong?

First deinstall the regular version. Then open the Testflight Link on the Safari within your AVP. It should start the Testflight where you accept the terms. You should have a 20.13.1 version then.

**Comment by hrgargi** [comment]
By the way: Refering to Handtracking: Leave it on presets at "SteamVR Input 2.0". There is no need to do any special settings. My Controllers are working with the Testflight 20.13 and the streamer 20.14.

**Comment by VoodooDE** [comment]
> By the way: Refering to Handtracking: Leave it on presets at "SteamVR Input 2.0". There is no need to do any special settings. My Controllers are working with the Testflight 20.13 and the streamer 20.14.

Thank you so much, will try it tomorrow 👍🏻

**Comment by VoodooDE** [comment]
> > > Hi Voodoo! You are sure you have the Testflight Version installed instead of the Appstore download? The Testflight is working with the PSVR2 Controllers. You then just have to rotate them a bit in the Streamer Software.
> > 
> > 
> > Hmm good question. So I went via the testflight link and accepted the terms. Where exactly do I have to install the testflight version then? I guess searching it in the store is wrong?
> 
> First deinstall the regular version. Then open the Testflight Link on the Safari within your AVP. It should start the Testflight where you accept the terms. You should have a 20.13.1 version then.

It worked!!! Thank you so much for your help!!

**Comment by hrgargi** [comment]
> > > > Hi Voodoo! You are sure you have the Testflight Version installed instead of the Appstore download? The Testflight is working with the PSVR2 Controllers. You then just have to rotate them a bit in the Streamer Software.
> > > 
> > > 
> > > Hmm good question. So I went via the testflight link and accepted the terms. Where exactly do I have to install the testflight version then? I guess searching it in the store is wrong?
> > 
> > 
> > First deinstall the regular version. Then open the Testflight Link on the Safari within your AVP. It should start the Testflight where you accept the terms. You should have a 20.13.1 version then.
> 
> It worked!!! Thank you so much for your help!!

Great to hear! Can't wait to see some reviews from you on YouTube.
Feel free to get some configuration hints on my community page:

https://vrfamilie.de/docs/apple-vision-pro/alvr-apple-vision-pro-fuer-steamvr-einrichten/

If you experience some micro stuttering while moving in some games like HL ALYX switch back to H264 with 3040 x 1072 on both settings. Scale it to 150% within Steam and you get 4K per eye again. HEVEC is mor stable, but I notice more jitter.

Enjoy your AVP!
